(in-package :chip-8-dynarec)

(defun compile-program (filename)
  (let* ((rom (read-rom-file filename))
         (name (string-upcase (file-namestring filename)))
         (name-symbol (intern name :chip-8-program))
         (program (make-program rom)))
    (compile name-symbol program)
    (setf (get name-symbol :code) program)
    (export name-symbol :chip-8-program)
    name-symbol))
